### ISSUE TITLE
并发超过250个左右后，就会出现数据丢失，为什么？

### ISSUE THREAD

**Issue by antyiwei** [vsco/mgopool#4]
read: connection reset by peer

**Comment by Tom-Kail** [comment]
你用的是leaky模式吧，用下capped模式试试
pool := mgopool.NewCapped(initial, 3)

**Comment by bigthyme** [comment]
@antyiwei I believe what you want is what @Tom-Kail is suggesting. Going to close this out for now, but if you have any further questions please write in and attach more detail to your request.

Thanks for contributing!
